### ISSUE TITLE
Show list of implemented interfaces

### ISSUE THREAD

**Issue by mfnalex** [zlataovce/takenaka#13]
The old mappings viewer showed a list of implemented interfaces, the new one doesn't. It would be nice if this could get added again.

![image](https://github.com/zlataovce/takenaka/assets/1122571/92695348-f771-4559-8d02-3285e0614c27)
![image](https://github.com/zlataovce/takenaka/assets/1122571/f19c9f9e-d264-4dba-9896-68f87562ac62)

**Comment by zlataovce** [comment]
Thank you for the suggestion, it should be available on the production deployment shortly.
