### ISSUE TITLE
Restrict search to certain namespace

### ISSUE THREAD

**Issue by mfnalex** [zlataovce/takenaka#14]
The old mappings viewer allowed to search in specific namespaces (Spigot, Mojang, Obfuscated, ...) while the new viewer doesn't allow this. It'd be nice if the filter could get added to the new version, too.

**Comment by Misat11** [comment]
Currently you can search in specific namespace by writing `ns:<namespace>` (eg. `ns:spigot`) before the searched term.

**Comment by zlataovce** [comment]
I plan to add a visual guide to the site that explains that and/or add it to the planned documentation (#9).

**Comment by zlataovce** [comment]
After more consideration, a namespace-choice component is more favourable for site users (multi-select, you'll still be able to search within all namespaces). This will be added to the site before the initial release and NMSMapper deprecation.
