### ISSUE TITLE
Ability to disable mappings (cli)

### ISSUE THREAD

**Issue by macbrayne** [zlataovce/takenaka#31]
Cool project! :)
Snapshots sadly break the history a bit as searge isn't available for them.
As an alternative to working out a way of dealing with presentation of a history where some mappings are not available on some versions I'd suggest a way of specifying which mappings get generated on the CLI.

![image](https://github.com/zlataovce/takenaka/assets/27809595/441987b8-0e22-4163-b181-00cd1644e075)

**Comment by zlataovce** [comment]
This has been implemented in https://github.com/zlataovce/takenaka/commit/820557eb198cd1a77685f88f9dbfb889123f855a for the next minor version (1.2.0). Thank you for your feedback!
