### ISSUE TITLE
missing net.minecraft.client.*

### ISSUE THREAD

**Issue by xHyroM** [zlataovce/takenaka#36]
is there any reason why it's missing on publis build? for now, i just build it locally

**Comment by zlataovce** [comment]
GitHub Pages, which is used for deployment, warns for deployments larger than one gigabyte and the current public build exceeds that with just server-side mappings, so I don't plan on pushing its limits with client-specific classes.

**Comment by xHyroM** [comment]
I hope it is not a problem that I deployed this project but also with client mappings :D - https://mappings.xhyrom.dev/
