### ISSUE TITLE
how to get mappings of some version as json or something else?

### ISSUE THREAD

**Issue by 00110001011100010111100001111010** [zlataovce/takenaka#41]
Is it possible to do this or not? I want to generate sdk based on these mappings.

**Comment by zlataovce** [comment]
there's no JSON format built into the library - if you want the mapping set displayed on https://mappings.cephx.dev in a machine-readable format, a mapping bundle is published on the [ScreamingSandals Maven repository](https://repo.screamingsandals.org/#/releases/me/kcra/takenaka/mappings/1.8.8+1.21)

it is a zip file with Tiny v2 mapping files named by their corresponding version, you can use [mapping-io](https://github.com/FabricMC/mapping-io) or [srgutils](https://github.com/MinecraftForge/SrgUtils) to read them
