### ISSUE TITLE
1.21.3 not found in manifest

### ISSUE THREAD

**Issue by Syrent** [zlataovce/takenaka#49]
When I try to add version `1.21.3` for `accessor` in the `versionRange`, I get the following error:
`Version 1.21.3 not found in manifest`.

Additional details:
- Takenaka plugin version: `1.2.1-SNAPSHOT`
- Mapping bundle: `1.8.8+1.21.3`
- Version range: `"1.8.8", "1.21.3"`

**Comment by zlataovce** [comment]
try removing the cached manifest from build/takenaka/cache/manifest.json and re-run the task
